### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by codysoyland** [pilosa/chem-usecase#1]
Please add a license to this. Should be consistent with https://github.com/alanbernstein/pilosa-notebooks/issues/2 which I think will be CC-BY. Check with Alan on this. Thanks!

**Comment by linhvo** [comment]
Thanks Cody! I added a license as you recommended. Let me know if there's any need to be changed in this commit.
https://github.com/pilosa/chem-usecase/commit/6964966de76018a18b03407a2d7531604db81fb8

**Comment by codysoyland** [comment]
Looks good, thanks @linhvo!
